import type { BenefitStat } from "./types";

export const benefits: BenefitStat[] = [
  {
    icon: "Clock",
    label: "دسترسی فوری به اطلاعات بیمار",
    description: "دسترسی زیر چند ثانیه به سوابق پزشکی هر کارمند در هر زمان و مکان.",
    tone: "amber",
    footerIcon: "MagnifyingGlass",
    footerLabel: "جستجوی زیر ۱ ثانیه",
  },
  {
    icon: "Pulse",
    label: "پایش مداوم و تشخیص سریع",
    description: "کشف زودهنگام علائم بیماری‌های شغلی پیش از بروز حاد.",
    tone: "emerald",
    footerIcon: "Scan",
    footerLabel: "ارزیابی پیشگیرانه",
  },
  {
    icon: "UserCheck",
    label: "حفظ نیروهای متخصص",
    description: "کاهش نرخ غیبت از کار و ارتقای حس وفاداری پرسنل کلیدی.",
    tone: "cyan",
    footerIcon: "ChartLineUp",
    footerLabel: "افزایش ماندگاری نیرو",
  },
  {
    icon: "LockKey",
    label: "امنیت پیشرفته برای داده‌ها",
    description: "رمزنگاری داده‌ها مطابق با بالاترین استانداردهای حفاظت پزشکی.",
    tone: "violet",
    footerIcon: "ShieldCheck",
    footerLabel: "رمزنگاری AES-256",
  },
  {
    icon: "Smiley",
    label: "افزایش رضایت و بهره‌وری",
    description: "ارتقای سطح سلامت سرمایه انسانی و بهبود کارایی کل مجموعه.",
    tone: "orange",
    footerIcon: "UsersThree",
    footerLabel: "بهبود بهره‌وری تیمی",
  },
  {
    icon: "ShieldCheck",
    label: "حفاظت از داده‌های حساس پزشکی",
    description: "سطوح دسترسی دقیق و محرمانه بودن کامل اطلاعات هر فرد.",
    tone: "indigo",
    footerIcon: "LockKey",
    footerLabel: "کنترل سطوح دسترسی",
  },
  {
    icon: "Scales",
    label: "تاریخچه پزشکی قابل استناد حقوقی",
    description: "پشتوانه متقن برای دادگاه‌ها، مراجع قانونی و اداره کار.",
    tone: "red",
    footerIcon: "FileText",
    footerLabel: "استناد قانونی کامل",
  },
  {
    icon: "NotePencil",
    label: "مستندسازی دقیق درمان و پیگیری",
    description: "ثبت تمام توصیه‌های طب کار، درمان‌ها و ارجاعات تخصصی.",
    tone: "teal",
    footerIcon: "ClipboardText",
    footerLabel: "ثبت ریز ارجاعات",
  },
];
